services:
  postgres:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_HOST: "${DB_HOST}"
    ports:
      - "${DB_PORT}:5432"
    container_name: walletsim